.PHONY: verify verify-g1 verify-g2 verify-g3 verify-g4 verify-g5

verify:
	$(MAKE) --no-print-directory -C .. verify

verify-g1:
	$(MAKE) --no-print-directory -C .. verify-g1

verify-g2:
	$(MAKE) --no-print-directory -C .. verify-g2

verify-g3:
	$(MAKE) --no-print-directory -C .. verify-g3

verify-g4:
	$(MAKE) --no-print-directory -C .. verify-g4

verify-g5:
	$(MAKE) --no-print-directory -C .. verify-g5