export const DESTINATION_RETRY_MAX_ATTEMPTS_CONFIG_KEY =
  'DESTINATION_RETRY_MAX_ATTEMPTS';

export const DESTINATION_RETRY_INITIAL_DELAY_MS_CONFIG_KEY =
  'DESTINATION_RETRY_INITIAL_DELAY_MS';

export const DESTINATION_RETRY_MAX_DELAY_MS_CONFIG_KEY =
  'DESTINATION_RETRY_MAX_DELAY_MS';

export const DEFAULT_DESTINATION_RETRY_MAX_ATTEMPTS = 10;

export const DEFAULT_DESTINATION_RETRY_INITIAL_DELAY_MS = 250;

export const DEFAULT_DESTINATION_RETRY_MAX_DELAY_MS = 5_000;
