export const CUSTOMER_INCREMENTAL_SYNC_JOB_NAME = 'customers';

export const INCREMENTAL_SYNC_BATCH_SIZE_CONFIG_KEY =
  'INCREMENTAL_SYNC_BATCH_SIZE';

export const INCREMENTAL_SYNC_POLL_INTERVAL_MS_CONFIG_KEY =
  'INCREMENTAL_SYNC_POLL_INTERVAL_MS';

export const DEFAULT_INCREMENTAL_SYNC_BATCH_SIZE = 100;

export const DEFAULT_INCREMENTAL_SYNC_POLL_INTERVAL_MS = 1_000;
