export const CUSTOMER_BACKFILL_JOB_NAME = 'customers';

export const BACKFILL_BATCH_SIZE_CONFIG_KEY = 'BACKFILL_BATCH_SIZE';
export const BACKFILL_BATCH_DELAY_MS_CONFIG_KEY = 'BACKFILL_BATCH_DELAY_MS';

export const DEFAULT_BACKFILL_BATCH_SIZE = 500;
export const DEFAULT_BACKFILL_BATCH_DELAY_MS = 0;
